### ISSUE TITLE
Case error in config/app-config-demo.json file

### ISSUE THREAD

**Issue by oidebrett** [aws-samples/aws-iot-greengrass-v2-using-aws-cdk#4]
config/app-config-demo.json file has lower case error in Public Component Shadow Manager configuration.

Iine 44 - configurationUpdate should be ConfigurationUpdate

**Comment by kwonyulchoi** [comment]
@oidebrett ,

Thank you for your comment.

This was my mistake, I fixed that.

Thanks again.
